[project]
name = "hermpy"
authors = [
    { name="Daragh Hollman", email="dhollman@cp.dias.ie" },
    { name="Charles Bowers", email="cbowers@cp.dias.ie"},
    { name="Caitriona Jackman", email="cjackman@cp.dias.ie"},
    { name="Adam Healy"}
]
description = "A collection of tools to aid in the creation of publication plots from spacecraft around Mercury."
keywords = ["Mercury", "Space Science", "Planetary Science", "Space", "MESSENGER", "BepiColombo", "Magnetospheres"]

readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent"
]
dependancies = [
    "numpy",
    "matplotlib",
    "ephem",
    "spiceypy",
    "pandas",
    "tqdm"
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/daraghhollman/HermPy"
Issues = "https://github.com/daraghhollman/HermPy/issues"


[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip_safe = false

[tool.setuptools.packages.find]

[tool.setuptools_scm]
write_to = "hermpy/version.py"
