[build-system]
requires = ["hatchling", ]
build-backend = "hatchling.build"

[project]
name = "MercuryTools"
version = "0.0.1"
authors = [
    { name="Daragh Hollman", email="dhollman@cp.dias.ie" },
    { name="Charles Bowers", email="cbowers@cp.dias.ie"},
    { name="Catriona Jackman", email="cjackman@cp.dias.ie"},
    { name="Adam Healy"}
]
description = "A collection of tools to aid in the creation of publication plots from spacecraft around Mercury."
keywords = ["Mercury", "Space Science", "Planetary Science", "Space", "MESSENGER", "BepiColombo", "Magnetospheres"]
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent"
]

dependancies = [
    "numpy",
    "matplotlib",
    "ephem",
    "spiceypy",
    "pandas",
    "tqdm"
]

[project.urls]
Homepage = "https://github.com/daraghhollman/MercuryTools"
Issues = "https://github.com/daraghhollman/MercuryTools/issues"
